# Site settings
title: Chocolate Jar
email: info@chocolatejar.eu
description: "DECADENTLY DELICIOUS SOFTWARE IN JAVA & JAVASCRIPT"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/andrej_zachar
  - title: linkedin 
    url: http://nl.linkedin.com/pub/andrej-zachar/5/952/b68/
  - title: github
    url: http://github.com/azachar
  - title: briefcase
    url: http://blog.chocolatejar.eu
    
# Postal address (add as many lines as necessary)
address:
  - line: Zonstraat 11
  - line: 3581MN Utrecht, The Netherlands
  - line: KVK 56293593 
  - line: VAT ﻿NL787959649B01

# Build settings
markdown: kramdown
permalink: pretty
